### ISSUE TITLE
Stabilize happy-birthder tests

### ISSUE THREAD

**Issue by ABSLord** [tolstoyevsky/rocketchat-tests-based-on-splinter#96]

**Comment by eugulixes** [comment]
The following tests are unstable (sometimes work, sometimes don't):
* `test_specifying_date_birth_by_admin`
* `test_creating_birthday_channel`
* `test_reminder_of_upcoming_birthday_7_days_in_advance`
* `test_reminder_of_upcoming_birthday_1_days_in_advance`
* `test_birthdays_list_command_with_no_birthday`
* `test_invoking_birthdays_list_with_1_birth_date`
* `test_invoking_birthdays_list_with_2_birth_dates`

There was a situation when `test_creating_birthday_channel` was failed but `test_deleting_birthday_channel` was successful.
